### ISSUE TITLE
Files in the "static" folder are not served

### ISSUE THREAD

**Issue by kbash09** [aws-samples/eb-node-express-sample#1]
When I clone the repo and run it locally on my machine (not in Beanstalk), the static files are not served. The following line needs to be added to app.js:

``` javascript
app.use('/static', express.static('static'));
```

![screen shot 2015-11-19 at 9 45 05 am](https://cloud.githubusercontent.com/assets/1813189/11278900/53701776-8ea2-11e5-92da-0e75abe902f8.png)

**Comment by abhiksingh** [comment]
On AWS Elastic Beanstalk, this is not necessary as the proxy server (Nginx) is setup to serve static assets. This reduces load on the Node process as Nginx is more efficient at serving files. You could do the same on your local machine or simply comment those lines when uploading to Elastic Beanstalk.

**Comment by PeterLD** [comment]
I just started going through the tutorial, and /static doesn't seem to be served by default anymore. It works after manual configuration, but it should either be documented in the tutorial or updated in the codebase to not need it.

**Comment by abhiksingh** [comment]
The /static path is setup by the [configuration file](https://github.com/awslabs/eb-node-express-sample/blob/master/.ebextensions/options.config) and when deploying the code to Elastic Beanstalk, you should not need the line above to setup the static route. @PeterLD could you double check that the configuration files are indeed being deployed to the EB environment.

**Comment by manast** [comment]
this is an insane behaviour, and the least I would expect is that the appropriate entries in the elasticbeanstalk interface do show that there is this "secret" static server serving files...
![image](https://user-images.githubusercontent.com/95200/34951799-b9468d9a-fa17-11e7-8757-3d6e420b70d4.png)

**Comment by nemethricsi** [comment]
> I just started going through the tutorial, and /static doesn't seem to be served by default anymore. It works after manual configuration, but it should either be documented in the tutorial or updated in the codebase to not need it.

still not updated in the tutorial

**Comment by nemethricsi** [comment]
> On AWS Elastic Beanstalk, this is not necessary as the proxy server (Nginx) is setup to serve static assets. This reduces load on the Node process as Nginx is more efficient at serving files. You could do the same on your local machine or simply comment those lines when uploading to Elastic Beanstalk.

This is doesn't seem to be solved. Please upen up the issue.
![Screenshot 2020-05-17 at 17 45 03](https://user-images.githubusercontent.com/35897699/82153169-2ef33b80-9866-11ea-93cf-c9d8dcaef1c6.png)
