### ISSUE TITLE
Signup does not work

### ISSUE THREAD

**Issue by lakamsani** [aws-samples/eb-node-express-sample#2]
no errors during "eb deploy" or "eb open". Was able to change the THEME variable and it works. However sign-up feature in the app does not work. After saving the form, the following error is seen in the app. 
<img width="768" alt="screen shot 2016-08-18 at 9 46 50 pm" src="https://cloud.githubusercontent.com/assets/3322496/17799199/59e6cf4c-658d-11e6-9468-3d87dfa2e0ca.png">
## /var/log/nodejs/nodejs.log

Server running at http://127.0.0.1:8081/
Server running at http://127.0.0.1:8081/
DDB Error: AccessDeniedException: User: arn:aws:sts::033780534505:assumed-role/aws-elasticbeanstalk-ec2-role/i-e47cce70 is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-west-2:033780534505:table/awseb-e-32wxzq4zap-stack-StartupSignupsTable-KJ2FDBKQNZEF
Server running at http://127.0.0.1:8081/
DDB Error: AccessDeniedException: User: arn:aws:sts::033780534505:assumed-role/aws-elasticbeanstalk-ec2-role/i-e47cce70 is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-west-2:033780534505:table/awseb-e-32wxzq4zap-stack-StartupSignupsTable-KJ2FDBKQNZEF

**Comment by abhiksingh** [comment]
Appears that the IAM instance profile associated with your environment doesn't have the necessary permissions. Please ensure that the IAM instance profile contains the permissions listed in iam_policy.json file.

**Comment by lakamsani** [comment]
hi, as this is a EB sample, should "eb deploy" not already apply that policy? Please add the instructions to README.md or update the EB setup to apply the IAM policy.

**Comment by abhiksingh** [comment]
The EB CLI doesn't automatically create policies for these sample applications. I've updated the README.md to include a list of steps necessary to run the sample.
