### ISSUE TITLE
CSS not loading locally

### ISSUE THREAD

**Issue by mraak** [aws-samples/eb-node-express-sample#8]
Node v7.7.3.

Apart from CSS not loading I get this logged four times:
```
Server running at http://127.0.0.1:3000/
Server running at http://127.0.0.1:3000/
Server running at http://127.0.0.1:3000/
Server running at http://127.0.0.1:3000/
```

**Comment by abhiksingh** [comment]
The application is setup to serve the static assets using the proxy server (Nginx) on the Elastic Beanstalk Node.js platform. To test this locally, you'd need to setup a static route to the /static folder.
